
services:
  nestapp:
    image: martintavella/nest-demo
    ports:
      - "3001:8080"
    env_file:
      - .env.development
    depends_on:
      - postgresdb
  postgresdb:
    image: postgres
    volumes:
     - pgdata:/var/lib/postgresql/data
    env_file:
     - .env.development

volumes:
  pgdata: